export const GET_PRODUCTS = 'GET_PRODUCTS'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_PRODUCT = 'SET_PRODUCT'

export const GET_EVENTS = 'GET_EVENTS'
export const SET_LOADING_EVENTS = 'SET_LOADING_EVENTS'
export const SET_ERROR_EVENTS = 'SET_ERROR_EVENTS'

export const GET_ORDERS = 'GET_ORDERS'
export const SET_LOADING_ORDERS = 'SET_LOADING_ORDERS'
export const SET_ERROR_ORDERS = 'SET_ERROR_ORDERS'

export const GET_ORDERS_HEADER = 'GET_ORDERS_HEADER'
export const SET_LOADING_ORDERS_HEADER = 'SET_LOADING_ORDERS_HEADER'
export const SET_ERROR_ORDERS_HEADER = 'SET_ERROR_ORDERS_HEADER'